jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - restore_cache:
          key: yarn-packages-{{ checksum "./yarn.lock" }}
      - run: yarn --frozen-lockfile
      - run: yarn format
      - run: yarn test
      - save_cache:
          key: yarn-packages-{{ checksum "./yarn.lock" }}
          paths:
            - ~/.cache/yarn
orbs:
  node: circleci/node@4.0.1
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
